disabled_rules:
  - line_length
  - trailing_whitespace
  - orphaned_doc_comment
  - nesting
  - function_body_length
  - large_tuple

force_cast: warning
included:
excluded:
  - Pods
  - Hyangyu/Sources/AppDelegate.swift
  - Hyangyu/Sources/SceneDelegate.swift

identifier_name:
  min_length:
    error: 1
  excluded:
    - id
  allowed_symbols: ["_"]
