# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hyangyu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hyangyu
	pod 'Moya', '~> 14.0'
	pod 'SwiftLint'
	pod 'SnapKit'
	pod 'Then'
	pod 'Kingfisher'
	pod 'Tabman', '~> 2.11'
end
